bitgouel-domain/src/main/kotlin/team/msg/domain/school/enums/HighSchool.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt
StudentActivity 엔티티와 HighSchool Enum에 있는 오타들을 수정했습니다
* StudentActivity credit의 자료형이 Int가 아닌 String으로 선언되어있던 오타를 수정했습니다
* HighSchool enum의 타입 대부분의 이름들이 소문자로 표기되어있던 오타를 수정했습니다
=> 18 entity and enum typing error

bitgouel-api/src/main/kotlin/team/msg/common/aop/HttpLoggingAspect.kt, bitgouel-api/src/main/kotlin/team/msg/common/init/DataInitializer.kt
RestController로 들어오는 http severt request, response, info를 로깅하는 aspect를 작성했습니다.
아래와 같은 내용을 로깅합니다
```kt
log.info(
"At {}#{} [Request:{}] IP: {}, Session-ID: {}, URI: {}, Params: {}, Content-Type: {}, User-Agent: {}, Headers: {}, Parameters: {}, Code: {}",
className, methodName, method, ip, sessionId, uri, params, contentType, userAgent, headerSet, params(proceedingJoinPoint), code
)
```
- 각 request,response마다 고유한 id를 부여합니다.
- `ResponseEntity<*>`의 response 타입을 로깅하는 로직에서 ResponseEntity타입이 반환되지 않으면 유효하지 않은 컨트롤러 반환 타입의 메시지로 RuntimeException이 발생하게 됩니다.
=> #44 HttpLoggingAspect 클래스 작성

bitgouel-api/src/main/kotlin/team/msg/domain/auth/exception/InvalidRefreshTokenException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/exception/RefreshTokenNotFoundException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/exception/constant/AuthErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/AuthController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/auth/model/RefreshToken.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/auth/repository/RefreshTokenRepository.kt
토큰 재발급
* 토큰 재발급 기능 구현
* 헤더로 refresh Token 요청받기
* 토큰 재발급 api 접근권한 추가
* RefreshToken data 클래스로 변경
=> # 45 토큰 재발급

bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-domain/build.gradle.kts, bitgouel-domain/src/main/kotlin/team/msg/common/entity/BaseUUIDEntity.kt, bitgouel-domain/src/main/kotlin/team/msg/common/ulid/ULIDGenerator.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/admin/model/Admin.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/bbozzak/model/Bbozzak.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/company/model/CompanyInstructor.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/government/model/Government.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/professor/model/Professor.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/Student.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/teacher/model/Teacher.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/model/User.kt
Persistable 클래스를 상속해 엔티티 관련 처리 연산에 효율을 올리도록 하겠습니다.
Persistable을 사용하기 위해 다음과 같은 이슈들을 해결해야합니다.
그래서 ULID를 Entity를 생성할 때 함께 생성해서 영속화를 하면 `EntityManager.persist` 함수가 아닌 `EntityManager.merge` 함수가 호출됩니다. 그래서 아래와 같이 저장하기 전에 Primary Key를 가진 데이터가 존재하는지 여부를 확인하는 쿼리가 한번 실행됨을 볼 수 있습니다.
> ULID 생성 이유는 UUID를 사용시 정렬과 같은 작업에서 성능이슈가 있을 수 있기 때문에 ulid를 부여해 엔티티의 순서를 보장하고 정렬에서 성능상 이점을 가져갈 수 있습니다.
ULIDGenerator로 ULID 생성 알고리즘을 작성한 후 엔티티 생성 시 ULID를 할당해줍니다.
<br>
> 그 이유는 JpaRepository deletee구현체에서 isNew()가 true라면 delete연산이 수행되지 않습니다.
```kt
@Override
@Transactional
@SuppressWarnings("unchecked")
public void delete(T entity) {
Assert.notNull(entity, "Entity must not be null!");
if (entityInformation.isNew(entity)) {
return;
}
Class<?> type = ProxyUtils.getUserClass(entity);
T existing = (T) em.find(type, …
```
=> BaseUUIDEntity() Persistable 구현과 JpaRepository 기능 관련 이슈 해결 트러블슈팅

bitgouel-api/src/main/kotlin/team/msg/domain/student/handler/StudentActivityEventHandler.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/event/UpdateStudentActivityEvent.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivityHistory.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentActivityHistoryRepository.kt
학생 활동을 업데이트 했을 때 PENDING으로 처리됩니다.
그렇기에 기존 업데이트 전 활동을 보존하기 위해 학생활동 History를 저장하는 로직을 처리합니다.
다음과 같은 프로세스를 가집니다.
**학생 활동 업데이트 -> 학생 활동 업데이트 이벤트 발행 -> 학생 활동 핸들러에서 히스토리 저장 관련 로직 처리**
History는 업데이트 되기 전 정보를 저장해야하기 때문에 트랜잭션 페이즈를 `Before Commit`으로 설정했습니다.
> 학생 활동 히스토리는 기본적인 StudentActivity의 필드와 StudentActivity의 아이디만 가지고 있습니다.
학생활동히스토리 엔티티에는 student, teacher의 엔티티를 `FetchType.LAZY`로 연관관계가 매핑되어있지만 단지 History READ를 위해 목적을 가지고 사용될 필드라면 이름만 저장하는 것도 어떨까 하는 생각이 들기는 합니다. 그러나 부가적인 변경사항이나 기능을 위해 안정적으로 일단 객체로 연관관계를 매핑해두었습니다.
@ani2689 
학생 활동 전체 조회 기능을 구현하는 과정에서 그저 Approved의 학생활동을 가져오는 것이 아닌 PENDING상태지만 History가 있는지 판별을 해야합니다. ApproveStatus는 업데이트 대기중 상태가 따로 존재하지 않기 때문에 필터링을 처리해야합니다. findAll()로 전부 가져와 필터링을 하는 과정을 밟을 수 있지만 쿼리지향적으로 처리할 수 있을 것 같습니다.
**다음과 같은 솔루션을 제시해드리겠습니다.**
-> select 쿼리로 approve상태인 학생 활동과 …
=> #56 학생 활동 업데이트 히스토리 저장 이벤트 핸들러 작성

bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/handler/StudentActivityEventHandler.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/common/entity/BaseUUIDEntity.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/admin/model/Admin.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/bbozzak/model/Bbozzak.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/company/model/CompanyInstructor.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/government/model/Government.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/professor/model/Professor.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/Student.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivityHistory.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/teacher/model/Teacher.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/model/User.kt
아이디 필드에 자동으로 생기는 게터 getId와 Persistable의 getId의 이름 충돌이 있어
@JvmName어노테이션으로 id값의 게터이름을 getIdentifier로 지정해 충돌을 막았습니다.
isNew()의 로직을 변경했습니다.
BaseUUIDEntity `isNew()`, id + All Of Entity
업데이트, 객체생성 관련할때 아이디값 다시 지정해서 인스턴스 생성해주시면 됩니다.
=> #62 getIdentifier 충돌 이슈 해결

Dockerfile, bitgouel-api/src/main/kotlin/team/msg/global/config/RedisConfig.kt, docker-compose.yml
docker compose (redis 환경 구성) 작성
RedisConfig 클래스 작성
redis는 main api 서버만 사용하고 있으니 elasticache를 사용하지않고 
Docker Compose를 통해서 사용하도록 하겠습니다.
\+ Dockerfile에 jar파일을 COPY하는 부분에서 bitgouel-api 모듈 경로 명시가 되어있지않아 이미지가 copy되지 않는 이슈를 해결했습니다.
=> 79 feat/docker compose redis

bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/teacher/model/Teacher.kt
동아리 상세 조회 API 개발
Teacher 와 Club 의 연관관계를 1:1 로 변경해주었습니다.
count jpa method 를 사용해 동아리에 속한 학생 수를 구했습니다.
=> #104 동아리 상세 조회 API 개발

bitgouel-api/build.gradle.kts, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllLectureRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/web/CreateLectureWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/web/QueryAllLecturesWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/handler/StudentActivityEventHandler.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/config/QueryDslConfig.kt, bitgouel-domain/build.gradle.kts, bitgouel-domain/src/main/kotlin/team/msg/common/enums/ApproveStatus.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/LectureStatus.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/LectureType.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/LectureRepositoryCustom.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/LectureRepositoryCustomImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivityHistory.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/model/User.kt
querydsl 세팅과 lecture list 필터 작업을 리팩토링했습니다.
- querydsl을 세팅했습니다.
- querydsl config를 작성했습니다.
- lecture repository custom을 작성했습니다.
- lecture list를 조회하는 과정에서 pending상태의 강의를 조회할 때 수강신청인원을 registered lecture repo를 통해 조회하는 과정을 생략하였습니다.
- 패키지명을 enum에서 enums로 변경했습니다.
- bitgouel-domain의 build.gradle.kts를 빌드해주면 QClass가 생성됩니다.
- ![image](https://github.com/GSM-MSG/Bitgouel-Server/assets/106813267/f407aeca-6be0-4c50-9fad-b85aab2008fa)
=> 101 feature/setting querydsl

bitgouel-api/src/main/kotlin/team/msg/common/init/DataInitializer.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/ClubRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/CustomClubRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/CustomClubRepositoryImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/school/repository/CustomSchoolRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/school/repository/CustomSchoolRepositoryImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/school/repository/SchoolRepository.kt, scripts/deploy.sh
DataInitializer 데이터 존재 여부 count 쿼리 성능을 개선했습니다.
ClubRepository `exsitsOne`: Club 데이터가 한 개 존재하는지 검증하는 로직
SchoolRepository `exsitsOne`: School 데이터가 한 개 존재하는지 검증하는 로직
DataInitializer가 실행이 된 어플리케이션이라면 id가 1인 School Club 엔티티가 존재합니다.
1인 엔티티가 존재하는지에 대한 여부에 따라서 data init 작업을 실행할지 검증합니다.
원래는 `count() == 0` 일때 실행했지만 이렇게된다면 데이터를 전부 count 하는 불필요한 연산이 발생됩니다.
관련 이슈를 해결하는 솔루션으로 이 방법을 채택했습니다.
**CustomClub, School Repository**
exists 관련한 로직이 필요하다면 이러한 로직을 사용해보는 것도 추천드립니다.
=> #119 DataInitializer 데이터 존재 여부 count 쿼리 성능 개선

bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
학생 활동 상세 조회 api를 작성하였습니다
학생 활동 api를 통해 학생 활동을 상세 조회할 수 있도록 하였습니다
해당 학생 활동과 관련된 역할과 어드민만 조회할 수 있도록 하였습니다
=> 114 학생 활동 상세 조회 api 개발

bitgouel-api/src/main/kotlin/team/msg/common/aop/log/HttpLoggingAspect.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
AOP를 사용하려 했으나 함수에 대한 제약 조건이 별로 있지 않기 때문에 하지 않았습니다.
StudentAcitivty 부분 검증 로직을 수정합니다.
추가로 infix 함수를 적용해 find is null throw 관련 로직을 단순화 했습니다.
다른 도메인 서비스들도 적용해보면 좋을 것 같습니다.
- StudentActivity 검증 로직 수정
- StudentActivity find infix 함수 적용
예외를 던지는 로직이 중복되어있기 때문에 함수 분리보단 이렇게 infix 함수로 간결하게 표기할 수 있도록 했습니다.
```kt
/**
* find ?: throw 로직을 단순화시킨 infix 함수들입니다.
*/
private infix fun StudentRepository.findByUser(user: User): Student =
this.findByUser(user) ?: throw StudentNotFoundException("학생을 찾을 수 없습니다. info : [ userId = ${user.id} ]")
private infix fun StudentActivityRepository.findById(id: UUID): StudentActivity =
this.findByIdOrNull(id) ?: throw StudentActivityNotFoundException("학생 활동을 찾을 수 없습니다. info : [ studentActivityId = $id ]")
private infix fun TeacherRepository.findByUser(user: User): Teacher = …
```
=> StudentActivity 검증 id 비교에서 동등비교로 수정합니다. + find infix 함수 적용

bitgouel-domain/src/main/kotlin/team/msg/domain/certifiacation/model/Certification.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/certifiacation/repository/CertificationRepository.kt
Certification 도메인 개발
Certification Entity 생성
Certification Repository 생성
=> # 127 Certification 도메인 개발

bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/request/CreateStudentActivityRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/request/UpdateStudentActivityRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/web/CreateStudentActivityWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/web/UpdateStudentActivityWebRequest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivityHistory.kt
학생 활동 엔티티의 활동 날짜에 불필요한 시간/분/초까지 들어가 있어 날짜만 저장되게 하였습니다
StudentActivity Entity activityDate column type DATETIME(6) -> DATE
CreateStudent(Web)Request activityDate 타입 LocalDate로 변경
UpdateStudent(Web)Request activityDate 타입 LocalDate로 변경
StudentActviityDetail Response 타입 변경
=> 133 활동 날짜의 데이터 타입을 Date로 변경

bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/CertificationController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/data/response/CertificationResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/FaqController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/data/response/FaqResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FaqService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/certifiacation/repository/CertificationRepository.kt
자격증 리스트 조회 학생 API 개발
학생을 조회할 때 infix 함수를 적용해 가독성을 높였습니다.
자격증 리스트를 조회할 때 studentId 가 권한에 따라 필요할 때도 있고 없을 때도 있어 api 를 학생용과 취동샘용, 2개로 나누었습니다.
=> # 126 자격증 리스트 조회 학생 API 개발

bitgouel-api/src/main/kotlin/team/msg/domain/certification/exception/CertificationNotFoundException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/mapper/CertificationRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/mapper/CertificationRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/CertificationController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/data/request/UpdateCertificationRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/data/web/UpdateCertificationWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/main/resources/application.yml
자격증 수정 API 개발
webRequest 를 비지니스 로직에서 사용하는 dto 로 매핑합니다.
204 No Content 를 반환합니다.
자격증을 생성한 사람이 본인인 지 검증합니다.
=> # 142 자격증 수정 API 개발

scripts/deploy.sh
deploy.sh 스크립트에서 배포 과정이 잘못되어 cd가 적용되지 않았습니다.
새로운 플로우를 정의하여 해결하겠습니다.
다음과 같은 과정으로 배포를 진행합니다.
Git Pull -> Multimodule gradlew build -> :8080 프로세스 존재 확인/취소 -> JAR 파일 무중단 배포(로깅 기록)
`deploy.sh` 수정
=> deploy sh 배포 플로우 수정

bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/response/TokenResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/jwt/JwtTokenGenerator.kt
로그인 시 response 에 Authority 추가
학생활동 승인에 권한을 식별하는 게 필요해 로그인 시에 Authority 를 추가로 반환해줍니다.
=> # 162 로그인 시 response 에 Authority 추가

bitgouel-api/src/main/kotlin/team/msg/domain/admin/mapper/AdminMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/mapper/AdminMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/data/request/QueryUsersRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/data/web/QueryUsersWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/UserController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/CustomUserRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/CustomUserRepositoryImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/UserRepository.kt
유저를 전체 검색하거나 이름을 통해 검색하는 기능을 개발하였습니다
* userList를 페이징 처리하기 위하여 userRepository에 findAll 재정의
* user를 keyword에 맞게 검색하기 위한 findByNameContaining 쿼리 메소드 재정의
* API 명세서에 정의된 Response 필드들을 반환하기 위한 UsersResponse 클래스
* 페이징 처리된 user를 Response로 변환하기 위한 listOf 함수 오버로딩
=> 137 유저 전체 조회 및 검색 api

bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
학생 활동 학생 단위로 조회 시 아무런 문제가 없는데도 학생을 찾지 못하였을 때 발생하는 404 status의 경위를 확인하여 보니 파라미터로 받아온 학생 id를 사용하고 있던 것이 아닌 AccessToken에 담긴 user를 통해 조회하고 있었습니다.
* 파라미터로 받아온 학생 id로 조회하도록 변경
* StudentRepository.findById infix 함수 정의
=> 180 feat/query student activity bug

bitgouel-api/src/main/kotlin/team/msg/domain/post/mapper/PostRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/request/CreatePostRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/request/UpdatePostRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/response/PostResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/CreatePostWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/UpdatePostWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/post/model/Post.kt
api 명세서에 따라 link -> links 로 이름을 변경했습니다.
- web request data의 link를 links로 변경
- post entity의 link 컬럼명을 links로 변경
=> 196 link -> links 로 이름 변경 

bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt
게시글 삭제 api의 권한 검증 로직을 리팩토링했습니다.
게시글 타입에 따라 삭제에 대한 권한 검증을 따로 처리하도록 했습니다.
=> 게시글 삭제 권한 검증 로직 리팩토링

bitgouel-domain/src/main/kotlin/team/msg/domain/post/model/Post.kt
Post의 user_id 컬럼에 columnDefinition 옵션을 추가했습니다.
user_id 컬럼을 binary 데이터 타입으로 지정해주었습니다.
=> Post의 user_id 컬럼에 columnDefinition 옵션을 추가했습니다.

bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
user save 코드 삭제
CasCade Merge type 으로 유저와 1:1 로 관계가 맺어진 학생(교수, 기업강사 ..)를 save할 때 user도 같이 save가 되기 때문에 user save 코드를 삭제 해주었습니다.
=> 185 user save 코드 삭제

bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/request/CreateInquiryRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/response/InquiryResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/CreateInquiryWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/enums/AnswerStatus.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/Inquiry.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/InquiryAnswer.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/InquiryRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/custom/InquiryRepositoryCustom.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/custom/InquiryRepositoryImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/UserRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/impl/CustomUserRepositoryImpl.kt
- 문의사항 조희 어드민 API
- 문의사항 조회 유저 API
문의사항 조회 API를 개발했어요
문의사항에 질문, 질문상세로 분리했고 userId참조에서 그냥 ManyToOne으로 다시 바꿨습니다.
그 이유가 listOf 구현하면서 유저 네임하고 문의사항하고 같이 넘겨줘야했는데 그냥 매핑하기보다는
객체 탐색으로 편하게 구현하려구요
그리고 검색 기능을 구현하면서 user 검색 기능에서 keyword Like에 %옵션이 없더라구요 추가했습니다.
- UserRepositoryCustom
- Inquiry
[depapepe - START](https://www.youtube.com/results?search_query=start+depapepe) 이 기타곡 좋습니다.
=> 214 feat/query inquiry admin user

bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentResponse.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
동아리에 소속된 학생의 상세정보를 조회하는 api를 작성했습니다.
club id와 student id를 받아 학생의 상세정보를 조회합니다.
동아리에 소속된 학생 리스트를 반환하는 StudentResponse에서, student id가 아닌 user id를 반환하고 있어 번경해주었습니다.
=> 동아리에 소속된 학생의 상세정보 조회 api

bitgouel-api/src/main/kotlin/team/msg/domain/student/handler/StudentActivityEventHandler.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/event/ApproveStudentActivityEvent.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/custom/CustomStudentActivityHistoryRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/custom/impl/CustomStudentActivityHistoryRepositoryImpl.kt
학생 활동 승인시 이전의 히스토리 삭제 후 가장 최신의 히스토리만을 저장하도록 eventHandler를 통해 처리했습니다
* ApproveStudentActivityEvent
* ApproveStudentActivityEventHandler
학생 활동 승인 시 ApproveStudentActivityEvent를 발행하는 코드가 추가되었습니다
=> 178 학생 활동 승인 시 학생활동 히스토리 업데이트

bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/InquiryRepository.kt
동아리 조회 관련 API 분리
* 동아리 Id를 이용한 동아리 상세 조회 기능의 접근 권한을 수정 해주었습니다.
* * 동아리 Id를 이용한 동아리원 상세 조회 기능 접근 권한을 수정 해주었습니다.
* 자신이 속한 동아리 조회 API를 개발했습니다.
* 자신이 속한 동아리 소속 유저 리스트 조회 API를 개발했습니다.
* 동아리 전체 조회에 학교 이름 추가 반환
=> # 217 동아리 조회 관련 API 분리

bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/SchoolController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/data/response/SchoolResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentResponse.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
동아리 상세 조회 및 동아리 부원 조회 API 병합
동아리 상세 조회 및 동아리 부원 조회 API를 병합 해주었습니다.(어드민용 / 동아리에 소속된 유저용 으로 나누어 작업 했습니다.)
headCount를 쿼리를 날리는 대신 size를 이용해 바꾸어 주었습니다.
student 반환은 StudentResponse 클래스를 이용해 주었습니다.
=> # 219 동아리 상세 조회 및 동아리 부원 조회 API 병합

bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/request/QueryAllInquiresWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/QueryAllInquiresRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/custom/InquiryRepositoryImpl.kt
GET /inquiry/all 조회 시 널포인터 예외가 발생하는 걸 고쳤습니다.
로깅을 담당하는 aop가 param에 null을 허용하지 않아 발생하는 문제였습니다.
따라서 param을 dto에 담아 얻어옴으로써 문제를 해결했습니다.
문의사항 검색 시 .like()를 사용하는데, 키워드 양 옆에 %를 허용하는 게 .contains()와 다를 게 없어서... 이참에 가독성 따져 바꿔주었습니다.
=> 234 feature/fix admin query inquiry

bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
소속 동아리 조회 동아리 Id 추가 반환
* 기존에 상세 조회에서는 ClubDetailsResponse를 동일하게 사용하였지만 MyClubDetailsResponse 클래스를 추가하여 리턴 타입을 다르게 설정 해주었습니다.
=> # 236 소속 동아리 조회 동아리 Id 추가 반환

bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
요구사항이 변경됨에 따라, 뽀짝쌤도 동아리에 속한 학생의 학생활동 조회 허용하도록 변경하였습니다
뽀짝쌤도 소속 동아리 학생의 학생활동 조회 API 접근 가능
학생활동 상세정보 API에도 뽀짝쌤이 접근 가능하도록 허용하였는데 비즈니스 로직의 역할 검증 로직에서는 뽀짝쌤을 허용하지 않아서 다른 이슈를 통해 해결해보려고 합니다
=> 🔀 :: 뽀짝쌤도 동아리에 속한 학생의 학생활동 조회 허용

bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
학생 활동 상세 조회 권한 검증 로직을 리팩토링 했습니다
학생 활동 상세 조회 권한 검증 로직에서 학생 활동을 작성한 학생의 동아리와 뽀짝쌤의 동아리가 같지 않다면 접근하지 못하도록 하는 검증 로직을 추가하였습니다
=> 🔀  :: 학생 활동 상세 조회 API 권한 검증 로직 리팩토링

bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
* 유저 강제 탈퇴 기능 구현
* 기존 회원 가입 거절 url을 변경 해주었습니다.
* /admin/{user_id} url로 유저 강제 탈퇴 기능을 매핑 해주었습니다.
* 어드민만 접근할 수 있도록 설정 해주었습니다.
* WithdrawUserEvent를 발행해 user를 삭제 해주었습니다.
* 함수명이 조금 어색한데 더 좋은 함수명 있으면 제시해주세요!
=> # 252 유저 강제 탈퇴 기능 구현

bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/UserRepository.kt
어드민이 유저를 수락할 때 단일 뿐만이 아닌 일괄적으로 유저를 수락할 수 있도록 변경하였습니다
유저 회원가입 수락 API를 유저를 여러 명 수락 가능 하도록 변경하였습니다
유저 회원가입 수락 API가 받는 파라미터를 queryString으로 변경하였습니다
기존에 보내던 요청이 예를 들어 ```bitgouel-domain.co.kr/admin/user_id1``` 형식 이었다면
```bitgouel-domain.co.kr/admin?userId=userId1,userId2,userId3```로 변경해서 요청을 보내야 합니다
=> 🔀 :: 263 유저 수락 API 다수를 수락 가능하도록 변경

bitgouel-api/src/main/kotlin/team/msg/domain/admin/mapper/AdminMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/data/request/QueryUsersRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/data/web/QueryUsersWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/CustomUserRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/impl/CustomUserRepositoryImpl.kt
유저 리스트를 반환하는 어드민 api를 리팩토링 하였습니다
* 페이징 처리 시 사용되는 pageable 파라미터 삭제 (page, size, sort 파라미터 삭제)
* 유저의 회원가입 승인 상태를 나타내는 필드인 approveStatus를 검색 조건에 추가했습니다
더이상 페이징처리를 하지 않아도 됩니다
=> 🔀 :: 266 유저 리스트 api 리팩토링

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllLectureRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllLecturesWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomLectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
강의 개설 권한 변경 및 강의 approveStatus를 삭제했습니다.
- 강의 개설 api request에 userId를 추가했습니다. 
- 강의 리스트 조회 api QueryString에서 approveStatuse를 삭제했습니다.
- 강의 리스트 및 상세 조회 api response에서 approveStatuse를 삭제했습니다.
- 대기 중인 강의 수락 및 거절 api를 삭제했습니다.
- 강의 model에서 approveStatus를 삭제했습니다.
- 강의 최소 인원을 5, 최대 인원을 10으로 설정했습니다.
- 강의 개설 권한을 어드민으로 변경했습니다.
강사 추가에 관해서 디자인과 이야기 해본 결과, 유저를 검색해서 하는 방식으로 결정했어요. 추후에 강사 검색 api를 추가하겠습니다!
=> 269 강의 개설 권한 변경 및 강의 approveStatus 삭제

bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
자격증 조회 권한을 학생 상세 조회와 같게 변경
자격증 조회 서비스의 주석을 더 상세히 적어주었습니다.
자격증 조회 권한을 학생 상세 조회와 같게 변경해 주었습니다.
=> # 272 자격증 조회 권한을 학생 상세 조회와 같게 변경

appspec.yml
Script time out 시간 늘리기
기존에 스크립트 타임아웃 시간이 60초로 설정되어 제대로 배포되지 않는 경우가 있었습니다. 해결하기 위해 180초로 늘려주었습니다.
=> # 275 Script time out 시간 늘리기

bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/presentation/data/response/WithdrawStudentResponse.kt
탈퇴 예정자 리스트를 반환할 때 studentId 대신 userId를 반환하도록 변경했습니다
WithdrawStudentResponse에 studentId 대신 userId를 담아 반환하도록 of 함수 변경
=> 🔀  :: 탈퇴 예정자 response 변경

bitgouel-api/src/test/kotlin/team/msg/domain/admin/service/AdminServiceImplTest.kt
어드민 도메인의 서비스 로직 테스트 코드를 작성하였습니다
* queryUsers 테스트 코드 작성
* approveUsers 테스트 코드 작성
* rejectUser 테스트 코드 작성
* queryUserDetails 테스트 코드 작성
* forceWithdraw 테스트 코드 작성
=> 🔀 :: 289 어드민 도메인 테스트 코드 작성

bitgouel-api/src/main/kotlin/team/msg/domain/user/handler/UserEventHandler.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/withdraw/repository/WithdrawStudentRepository.kt
student entity 삭제 시 withdraw student entity 함께 삭제
* withdraw student repository에 deleteByStudent 쿼리 메서드 정의
* withdrawUserHandler에서 student일 때 withdraw student 엔티티 삭제 로직 추가
=> 🔀  :: student entity 삭제 시 withdraw student entity 함께 삭제

bitgouel-api/src/main/kotlin/team/msg/domain/post/mapper/PostRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/CreatePostWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/UpdatePostWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/validation/URLList.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/validation/URLListValidator.kt
게시글 생성, 변경 시 url 검토 방식을 변경했습니다.
게시글 url을 String list로 받도록하고, custom validator를 추가해 url 형식을 검증하도록 했습니다.
게시글 생성, 변경 api의 url 입력을 String list로 변경했습니다.
url로 구성된 List<String>을 검증하고 싶을 때 구성요소 위에 @field:URLList를 붙여주면 됩니다!
=> 게시글 url 검토 방식 변경

bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/test/kotlin/team/msg/domain/admin/service/AdminServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/UserRepository.kt
유저를 거절할때 다수를 거절 가능하도록 변경하였습니다
유저 거절 api uri pattern /admin/{userId}/reject 와 PathVariable -> /admin/reject 와 queryString으로 변경
delete batch 쿼리를 위한 deleteByIdIn 쿼리 메소드에 @Modifying 어노테이션 사용
=> 🔀 :: 297 유저 거절 api 다수 거절 가능하도록 변경

bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/test/kotlin/team/msg/domain/student/service/StudentActivityServiceImplTest.kt
학생 활동 학생 단위 조회 API를 Admin도 접근 가능하도록 변경하였습니다
* 어드민도 접근 가능함에 따라 비즈니스 로직 리팩토링
* 추가된 분기문에 적합하도록 테스트 코드 수정
=> 🔀 :: 303 학생활동 학생 단위로 조회 API 권한 범위 변경

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/LectureDateRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/LectureDateWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/LectureDate.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureDateRepository.kt
강의 수강일을 적용했습니다.
강의 일자 테이블을 작성했습니다.
- 강의 일자 테이블에는 강의 날짜, 강의 시작 시간 및 종료 시간이 포함되어있습니다.
강의 테스트 코드에도 변경점을 적용해주었습니다.
- 수강 테이블에서 completeDate가 불필요해 삭제했습니다.
=> 강의 수강 날짜 단일 -> 리스트 적용

bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
어드민이 학생활동 학생 단위로 조회 시 401이 발생하던 문제를 수정하였습니다
securityconfig에 작성된 학생활동 학생 단위로 조회 uri pattern 어드민도 접근 가능하도록 수정
=> 🔀  :: 어드민 학생활동 학생 단위로 조회 접근 허용

bitgouel-api/src/main/kotlin/team/msg/domain/email/presentation/EmailController.kt
이메일 인증 링크 클릭 시 blank 페이지가 띄워지던 오류를 고쳤습니다.
- 인증 완료 후 문자열을 띄워 해결해주었어요!
=> 이메일 인증 링크 클릭 시 blank 페이지가 띄워지던 오류

bitgouel-api/src/main/kotlin/team/msg/domain/email/service/EmailServiceImpl.kt
이메일을 새로 전송할 때 코드가 새로 발급되지 않던 문제를 해결했습니다.
이메일 전송 시 코드를 새로 저장하도록 변경했습니다.
=> 이메일 새로 전송 시 코드 새로 발급

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/RegisteredLectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/RegisteredLectureServiceImpl.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
강의 수강을 동시에 신청했을 시 강의 수강 인원이 초과되어 신청되는 문제가 발생하여 이를 해결하였습니다
기존에 수강 신청 인원을 COUNT하는 쿼리에 비관적 락인 PESSIMISTIC_WRITE(SELECT ... FOR UPDATE)를 사용하여 두번의 갱실 문제 중 최초 커밋만 인정할 수 있도록 동시성을 제어하려 하였지만 예상했던 결과와 다르게 동시로 보낸 여러 요청 중 하나의 요청 빼고는 전부 실패하였습니다
이는 트랜잭션을 진행하던 도중 다음과 같은 경우에 의해 발생했던 것입니다
* 테이블의 레코드가 0개이며, SELECT ... FOR UPDATE 쿼리로 조회한 데이터가 0개인 경우
> 강의 신청이 시작되는 직후 다음과 같은 문제가 발생하였습니다
* 설령 테이블에 레코드가 존재한다 하더라도 둘 이상의 세션이 SELECT ... FOR UPDATE로 같은 id에 접근하는 경우
> 이는 같은 강의를 동시에 신청하는 경우에 발생하였습니다
이 두가지 경우는 모든 세션에서 INSERT문을 실행하지 못하게 되어 DeadLock이 발생하는 DB Level Issue가 있기 때문입니다
이를 해결하기 위해 수강 신청 인원을 COUNT 하는 쿼리를 @Lock(LockModeType.PESSIMISTIC_WRITE)옵션을 사용하며 DeadLock을 피하기 위해서 위의 로직을 새로운 클래스인 RegisteredLectureService로 옮긴 후 @Transactional(propagation = Propagation.REQUIRED_NEW)를 사용하여 새로운 트랜잭션을 실행하도록 하여 해결했습니다
해당 MySQL 이슈에 …
=> 🔀 :: 327 강의 수강신청 동시성 문제 해결

bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/presentation/data/response/WithdrawStudentResponse.kt
탈퇴 예정자 리스트 조회 시 인자 추가 반환
> 디자인 변경 사항에 따른 인자 추가해 주었습니다.
Resolves: #{370}
이메일, 전화 번호 추가 했습니다.
=> # 370 탈퇴 예정자 리스트 조회 시 인자 추가 반환

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllDivisionsRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllDivisionsWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomLectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
강의 구분을 사용자가 입력할 수 있도록 변경되었기에, 강의 구분 검색 api를 작성했습니다.
Resolves: #380 
- 서버에 저장된 강의의 division 리스트를 가져와 반환합니다.
- 다른 검색 api 로직과 같은 흐름으로 작동합니다!
- 감사합니다
=> 강의 구분 검색 api를 작성했습니다.

bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/request/GovernmentSignUpRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/GovernmentSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/government/model/Government.kt
유관기관 엔티티 필드 변경
Resolves: #{376}
직책 필드를 position 이라는 변수명으로 추가했습니다.
업종 필드를 sectors 라는 변수명으로 추가했습니다.
=> # 376 유관기관 엔티티 필드 변경

bitgouel-api/build.gradle.kts, bitgouel-api/src/main/kotlin/team/msg/global/warmup/WarmUpRunner.kt, bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/client/FaqClient.kt, bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/client/WarmUpClient.kt, bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/config/FeignConfig.kt, bitgouel-api/src/main/resources/application.yml, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/Student.kt
JVM 웜업
Resolves: #{387}
서비스 배포 직후 첫 요청에 대해 레이턴시가 발생합니다. 이유는 크게 두 가지입니다.
첫 번째, 클래스 로더가 애플리케이션이 시작될 때 로딩되는 것이 아닌 클래스가 필요한 시점까지 로딩을 지연하는 지연 로딩으로 작동합니다.
두 번째, JIT Compiler는 실행하는 과정에서 기계어로 변환하는 과정을 최적화 하기 위한 것입니다. 그러나, 애플리케이션이 처음 실행되는 시점에는 자주 사용되는 바이트코드가 캐시된 내역이 없기 때문에 성능 이슈가 발생합니다. 
자주 호출될 것으로 예상되는 API에 미리 요청을 보냄으로서 Warm-Up 하여 해결했습니다. (FAQ 조회 API를 메인 페이지에서 사용하기에 Warm Up 했습니다. 나중에 성능 테스트를 진행하면서 다른 API도 추가할 예정이며, 호출 횟수 또한 늘릴 가능성이 있습니다.)
=> # 387 JVM 웜업

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomRegisteredLectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomRegisteredLectureRepositoryImpl.kt
강의 이수 여부를 수정하는 api를 작성했습니다.
Resolves: #386 
- 강의에 신청한 학생들의 강의 이수 여부를 변경하는 api입니다.
- 권한 별로 이수 여부를 수정할 수 있는 학생의 범위를 다르게 하였습니다.
- 어드민 -> 모든 학생
- 뽀짝, 취동쌤 -> 소속 동아리 학생
- 강사 -> 자신이 강의하는 강의를 신청한 학생들만 (다른 강의 학생의 이수 여부를 변경할 시 예외)
감사합니다
=> 강의 이수 여부 수정 api 작성

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
유저가 학생일 때 자신이 신청한 강의 리스트를 볼 수 있도록 권한을 변경했습니다.
Resolves: #397 
- security config student 권한 추가
- student일 때 자신의 정보만 볼 수 있도록 조건문 추가
=> 유저가 학생일 때 자신이 신청한 강의 리스트를 볼 수 있도록 권한을 변경했습니다.

bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/email/service/EmailServiceImpl.kt, bitgouel-api/src/test/kotlin/team/msg/domain/auth/service/AuthServiceImplTest.kt
비밀번호를 변경한 후 일정 시간동안 인증이 남아있는 것을 확인했습니다. 비밀번호를 변경하면 인증을 초기화하도록 로직을 추가했습니다.
Resolves: #340 
- 비밀번호 변경 시 emailAuthentication을 삭제
- 위 테스트 코드 추가
- 가입하지 않은 유저는 이메일 인증 메일을 보내지 않도록 예외 추가
=> 비밀번호를 변경한 후 인증을 초기화하도록 로직을 추가했습니다.

scripts/deploy.sh
Jar 파일 실행 시 타임 존 설정
Resolves: #{414}
배포 환경에서 시간이 맞지 않는 문제를 해결하기 위해 타임 존 설정을 해주었습니다.
=> # 414 Jar 파일 실행 시 타임 존 설정

bitgouel-api/src/main/kotlin/team/msg/global/security/handler/CustomAccessDeniedHandler.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/handler/CustomAuthenticationEntryPointHandle.kt
401, 403  핸들러 처리가 반대로 되어있어서 수정했어요
Resolves: #436 
AuthenticationEntryPoint -> throw InvalidRoleException
AccessDeniedHandler -> ForbiddenException
=> handler 처리 반대로 된거 수정

README.md, bitgouel-api/src/main/kotlin/team/msg/common/util/StudentUtil.kt, bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/test/kotlin/team/msg/domain/auth/service/AuthServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/common/entity/BaseUUIDEntity.kt
JPA repository의 save 메서드 호출 시 해당 데이터가 존재하는지 확인하는 Select 쿼리를 발생시키지 않도록 하기 위해 Persistable의 isNew와 getId 메서드를 재정의했음에도 select쿼리가 발생했습니다
Resolves: #445 
id (Primary Key) 자동 생성 전략 삭제
기존에 엔티티 새로 생성 시 UUID.random()으로 설정해 놓은 것을 UUID(0, 0) (초기값을 가리키는 값)으로 삽입하도록 변경하였습니다
=> 🔀 :: 445 repository의 save 메서드 호출 시 성능 개선

bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/web/CreateFaqWebRequest.kt, bitgouel-api/src/main/resources/logback-spring.xml
FAQ 작성 Request Dto 필드 길이 설정
Resolves: #{452}
제목은 100자, 내용은 넉넉잡아 3000자로 설정했습니다.
logback 스캔 주기 1분으로 늘렸습니다.
=> # 452 FAQ 작성 Request Dto 필드 길이 설정

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
강의 상세조회 api에 강사의 유저 id 값을 추가했습니다.
Resolves: #474 
- 강의 상세조회 api response에 강사 유저 id값을 추가했습니다.
- 그에 맞춰 테스트 코드도 수정해주었습니다.
=> 강의 상세조회에 user id 값 추가

bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
삭제된 강의 데이터가 강의 리스트에서 조회되던 문제를 해결했습니다.
Resolves: #48 
custom repo에서 isDelete 조건을 추가해주지 않아 생긴 문제였습니다.
=> 삭제된 강의 데이터가 강의 리스트에서 조회되던 문제 해결

bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/impl/CustomUserRepositoryImpl.kt
강사가 조회되지 않는 버그를 고쳤습니다.
Resolves: #500 
강사 권한 별 기관 엔티티와 강사 엔티티가 나뉘어 중간 join문이 없어 생기던 버그였습니다. 
join 해주어 고쳤습니다!
=> 강사 조회 안되는 버그 수정

bitgouel-api/src/main/kotlin/team/msg/common/util/StudentUtil.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/request/StudentSignUpRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/StudentSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt, bitgouel-api/src/test/kotlin/team/msg/domain/admin/service/AdminServiceImplTest.kt, bitgouel-api/src/test/kotlin/team/msg/domain/auth/service/AuthServiceImplTest.kt, bitgouel-api/src/test/kotlin/team/msg/domain/certification/service/CertificationServiceImplTest.kt, bitgouel-batch/src/main/kotlin/team/msg/jobs/student/GraduateStudentJobConfiguration.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/Student.kt
가입 당시 학년 정보 추가
Resolves: #501
유저 전체 조회 API에서 가입 당시 학년 정보를 추가로 반환해줍니다. 학생이 아닌 유저의 경우 null을 반환합니다.
=> # 501 가입 당시 학년 정보 추가

bitgouel-api/src/main/kotlin/team/msg/domain/club/exception/AlreadyExistClubException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/exception/constant/ClubErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/mapper/SchoolRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/data/request/CreateSchoolRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/web/CreateSchoolWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/ClubRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/custom/CustomClubRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/custom/impl/CustomClubRepositoryImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/school/repository/custom/CustomSchoolRepository.kt
동아리 생성 및 동아리 이름 전체 조회 개발
Resolves: #515
동아리 수정에 없던 동아리 존재여부 유효성 검사를 추가했습니다.
동아리 이름 전체 조회 개발했습니다. 정렬은 학교 이름과 동아리 이름을 오름차순으로 정렬했습니다. 이 기능은 회원가입 시 사용되는 기능이기에 permitAll()로 설정했습니다.
학교를 생성하며 같이 생성하던 동아리를 따로 동아리 생성 기능으로 빼서 개발했습니다.
=> 515 동아리 생성 및 동아리 이름 전체 조회 개발

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/InvalidStudentGradeException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/constant/StudentErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/CompleteStatus.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomRegisteredLectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomRegisteredLectureRepositoryImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/projection/LectureProjection.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
강의 이수에서 요구하는 요구사항이 달라짐에 따라 API 로직을 변경했습니다.
Resolves: #519
https://www.notion.so/f13d8386b49e4375ac6e99b4e8943e2c?v=1b847b9c9db345f0ac2a085c69a45592&pvs=4
- 강의 신청 내역 조회 API 변경
- response의 isComplete를 completeStatus로 변경
- 강의 이수 중인 학생 전체 조회 API 변경
-  response에서 email, phoneNumber, cohort 삭제
- 강의 이수 중인 학생 상세 조회 API 개발
- 강의 이수 여부 변경 -> 강의 이수 완료로 목적 변경
- studentIds로 학생 이수 여부 일괄 완료 가능하게
- 매핑 url 변경
이수한 학년을 컬럼으로 추가할까 했는데 이수하기 전엔 null로 다룬다는 점이 조심...스러워서 enum으로 다루기로 했습니다...만! 다른 좋은 조언 있으시면 해주세요 :D
추가로 테스트 코드 수정은 pr이 머지된 후 하려고 합니다. 테스트코드를 지금 수정하기엔 양이 방대해 오래걸릴 것 같고,,. 또 엑셀 작업을 하기 위해선 일단 변경사항을 반영하는게 먼저라고 생각했어요~!
=> 강의 이수 API 변경사항 적용

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
강의 이수 변경사항 테스트코드 작성
Resolves: #523 
- 강의 이수중인 학생 상세조회 테스트코드 작성
- 강의 이수 여부 확인 테스트 코드에 save -> saveAll로 변경
- 반환 값 잘못 들어가있던거 수정
=> 강의 이수 변경사항 테스트코드 작성

bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/SchoolController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt
School LogoImage Required false
Resolves: #532
학교를 조회하는 API에서는 학교 이미지 URL을 반환합니다. 그러나 학교 이미지를 수정하기 위해서 Multipart 타입의 이미지로 요청해야 합니다. 이로인해 학교 이름을 수정하기 위해서 학교 이미지를 항상 보내야하는 상황이 발생하여 required false로 변경했습니다.
=> # 532 School LogoImage Required false

bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/school/repository/SchoolRepository.kt
기존 학교들의 이름 중복을 막기 위해 검색하는 과정에서 자신의 이름까지 중복 리스트에 포함하며 학교 수정 시 이름을 변경하지 않으면 학교 수정이 안되는 버그가 있었습니다.
자기 자신은 이름 검색에서 제외하여 해결했습니다.
Resolves: #536 
- 수정되는 학교 자기 자신은 학교 이름 리스트를 조회하는 데에서 제외
=> 학교 수정 시 학교 이름이 변경되지 않으면 학교 수정이 되지않는 버그를 고쳤습니다.

bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/ClubRepository.kt
동아리 수정 시 나타나던 버그를 고쳤습니다.
Resolves: #536 
- 동아리 수정 시 동아리 이름을 변경하지 않으면 동아리 수정 자체가 안되던 버그
- 요청된 이름의 동아리를 검색할 때 수정 대상의 동아리를 제외하고 조회하여 해결했습니다.
- 동아리 수정 시 새로운 동아리로 생성되던 버그
- id를 지정하지 않아 새로운 엔티티로 취급되어 추가로 저장되던 버그였습니다. id를 명시해 해결했습니다. 
=> 동아리 수정 시 나타나던 버그 수정

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllSignedUpStudentsRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllSignedUpStudentsWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomRegisteredLectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomRegisteredLectureRepositoryImpl.kt
강의 신청 학생 리스트를 이수 여부에 따라 필터링하여 조회할 수 있도록 변경했습니다.
Resolves: #561 
- webRequest 추가
- filter 과정 추가
registeredLecture에서 강의 이수 여부 정보를 가지고 있으나 enum으로 가지고 있어 조회 후 filter 고차함수를 이용해 필터링하는 방향으로 구현했습니다.
query param을 class로 다룬 이유는... 전에 언급했듯이 request 매핑해놓은 곳에 null이 들어온 순간 터져버리기 때문입니다... 
=> 강의 신청 학생 이수 여부에 따라 필터링하여 조회

bitgouel-api/src/main/kotlin/team/msg/global/config/RedissonConfig.kt
분산 락에서만 이용하는 redisson client가 필요 이상의 connection을 생성하고 있었습니다
Resolves: #565 
Redisson max connection 개수 10개로 제한
Redisson min connection 개수 5개로 제한
검색을 해본다고 해봤는데 뭔가 적합한 커넥션 개수를 딱히 찾기가 어려워 임의로 설정한 것이니 의견 있으시다면 자유롭게 다이렉트로 내주세요
=> 🔀 :: Redisson connection 개수 조정

bitgouel-api/build.gradle.kts, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/company/service/CompanyServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/government/service/GovernmentServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/university/service/UniversityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/config/CacheConfig.kt, bitgouel-api/src/main/kotlin/team/msg/global/config/properties/CacheProperties.kt, bitgouel-api/src/test/kotlin/team/msg/domain/club/service/ClubServiceImplTest.kt
메인 페이지에서 자주 조회되는 요소들을 매번 쿼리를 DB에 보내 데이터를 받아오는것이 비효율적이라고 생각되어 작업을 진행하였습니다
Resolves: #567 
메인페이지에서 조회되는 School, Club, Government, Company, University 엔티티를 조회하는 API에 캐싱을 적용하였습니다
또한 해당 엔티티에 대한 생성, 수정, 삭제 작업이 발생하면 캐시를 삭제하도록 하였습니다
조회하려는 엔티티마다 데이터의 크기 형태가 다르므로 캐시를 처음 적용해본 입장으로써 캐시 엔트리의 최대 수나 만료 기간등을 지정하는데 살짝 혼란이 있었습니다
=> 🔀 :: 공유 캐시 작업

bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/test/kotlin/team/msg/domain/admin/service/AdminServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/model/User.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/UserRepository.kt
강의 엑셀 일괄 삽입 API를 작성했습니다.
Resolves: #570 
- 강의 엑셀 일괄 삽입 API
- 강의 용어가 모호한게 좀 많아서 예시 데이터 row를 하나 잡았습니다. 그래서 0번 index와 1번 index를 건너뜁니다!
강사를 찾을 때 동명이인이 있을 수 있어 강사명과 이메일을 함께 조회하여 강사를 찾을 수 있도록 했습니다.
강의 날짜를....................... ,,,,,,,........파싱으로 잘 합의봤습니다.
강의 예시안은 노션에 올려놓았습니다. 참고 부탁드려요!
=> 강의 엑셀 업로드 API 작성
