bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/common/enum/ApproveStatus.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enum/LectureStatus.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enum/LectureType.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/enums/SignUpStatus.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/model/User.kt
강의 관련 엔티티와 레포를 작성했습니다.
- Lecture Entity & Repository
- Lecture Status & Type enum
- RegisteredLecture Entity  & Repository
=> 강의 관련 엔티티 세팅

README.md
커밋메세지 규율을 작성했습니다. 
마음에 들지 않거나 다르게 표기해서 사용하고 싶은 사항 있으면 리뷰남겨주세요
=> docs :: 커밋 메세지 규율 작성

bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/AuthController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/request/TeacherSignUpRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/TeacherSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/UserRepository.kt
취동샘 회원가입
* `createUser` 라는 private 함수로 user save 기능 구현
* 함수 주석으로 설명
* 취동샘 회원가입 기능 구현
* 취동샘 회원가입 api 접근권한 설정
* 취동샘 회원가입 webRequest 와 애플리케이션 dto 분리
=> # 24 취동샘 회원가입

bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt
학생 활동은 선생님이 승인을 해주어야 학점이 인정되는 요구사항으로 인하여 승인 상태를 나타내는 컬럼이 추가되어야 합니다
StudentActivity Entity에 approveStatus 컬럼을 추가하였습니다
=> 26 StudentActivity에 approveStatus 컬럼 추가

bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/AuthController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/request/ProfessorSignUpRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/ProfessorSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
대학교수 회원가입
* 대학교수 회원가입 기능 구현
* 대학교수 회원가입 api 접근권한 설정
* 대학교수 회원가입 webRequest 와 애플리케이션 dto 분리
=> # 31 대학교수 회원가입

bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/AuthController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/request/GovernmentSignUpRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/GovernmentSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
유관 기관 회원가입
* 유관 기관 회원가입 기능 구현
* 유관 기관 회원가입 api 접근권한 추가
* 유관 기관 회원가입 webRequest 와 애플리케이션 dto 분리
=> # 35 유관 기관 회원가입

bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/AuthController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/request/CompanyInstructorSignUpRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/CompanyInstructorSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/model/User.kt
기업 강사 회원가입
* 기업 강사 회원가입 기능 구현
* 기업 강사 회원가입 api 접근권한 추가
* 기업 강사 회원가입 webRequest 와 애플리케이션 dto 분리
=> # 37 기업 강사 회원가입

bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/StudentActivityNotFoundException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/constant/StudentActivityErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/mapper/StudentActivityMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/mapper/StudentActivityMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/request/UpdateStudentActivityRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/web/UpdateStudentActivityWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/common/entity/BaseTimeEntity.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentActivityRepository.kt
학생 활동 정보 수정을 작성하였습니다
* 학생 활동 controller 작성
* 학생 활동 service 작성
* 학생 활동 webDto, dto 작성
* 학생 활동 엔티티가 상속받는 createAt을 update 함수에 적용하기 위해 재정의 하였습니다
=> 48 feat/student activity update

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/AlreadyApprovedLectureException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/LectureNotFoundException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/constant/LectureErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
- 강의 개설 승인 및 거절 기능을 개발했습니다.
- 강의 개설 승인 비지니스 로직
- 강의 개설 거절 비지니스 로직
- 존재하지 않는 강의에 대한 예외
- 이미 승인된 강의에 대한 예외
=> 강의 개설 승인 및 거절 기능 개발

bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
학생 활동 거절 및 삭제 api를 만들었습니다
* 학생 활동 삭제 서비스
* 학생 활동 삭제 컨트롤러
학생만이 사용할 수 있는 api입니다
=> 54 feat/delete student activity

bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/ForbiddenStudentActivityException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/constant/StudentActivityErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentActivityRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/teacher/repository/TeacherRepository.kt
학생 활동 거절 및 삭제 기능을 작성하였습니다
* reject student activity service 작성
* reject student activity controller 작성
* studentActivity 리포지토리에 findByIdAndTeacher 쿼리 메소드 작성
=> 61 feat/student activity reject and delete

bitgouel-domain/src/main/kotlin/team/msg/domain/fAQ/model/FAQ.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/fAQ/repository/FAQRepository.kt
FAQ setting
baseUuidEntity를 상속받는 FAQ entity를 구현했습니다.
CrudRepository를 상속받는 FAQ repository를 구현했습니다.
=> # 66 FAQ setting

bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
학생 활동 승인 기능을 개발하였습니다
* Approve Student Activity Service
* Approve Student Activity Controller
* add SecurityConfig Endpoint
=> 68 feat/approve student activity

bitgouel-api/src/main/kotlin/team/msg/domain/faq/mapper/FAQRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/mapper/FAQRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/FAQController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/data/request/CreateFAQRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/web/CreateFAQWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/principal/AuthDetails.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/principal/AuthDetailsService.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/fAQ/model/FAQ.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/fAQ/repository/FAQRepository.kt
FAQ 등록 api
userDetails 에서 user 를 인자로 받게 수정했습니다.
FAQ 등록 api에 ADMIN만 접근할 수 있게 설정해주었습니다.
FAQ 등록 web request 와 비지니스 로직에서 사용하는 dto 를 mapper 를 이용해 변환해주었습니다.
=>  70 FAQ 등록 api

bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/FAQController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/data/response/QueryAllFaqsResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
FAQ 전체 조회
FAQ 전체 조회 로직을 구현하였습니다.
FAQ 전체 조회 api을 로그인을 할 경우 모두가 접근하게 설정해주었습니다.
=> 73 FAQ 전체 조회

bitgouel-api/src/main/kotlin/team/msg/domain/faq/exception/FaqNotFoundException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/exception/constant/FaqErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/FAQController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/data/response/FaqResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/data/response/QueryAllFaqsResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/data/response/QueryFaqDetailsResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/fAQ/model/FAQ.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/fAQ/repository/FAQRepository.kt
FAQ 상세 조회
FAQ id를 요청받아 그에 따른 FAQ를 반환해줍니다.
FAQ 상세 조회 api 에 접근 권한을 authenticated() 함수로 설정해주었습니다.
id 에 맞는 faq 가 존재하지 않으면 404 exception을 throw 해줍니다.
=> # 75 FAQ 상세 조회

bitgouel-api/src/main/kotlin/team/msg/domain/health/HealthCheckController.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
서버의 상태를 체크하는 HealthCheckController를 개발했습니다.
헬스체크 상태가 정상이면 OK, 라는 문구와 서버의 현재 포트를 response body로 전송합니다.
=> 82 Bitgouel Application HealthCheckController

.github/workflows/bitgouel-cd.yml, scripts/deploy.sh
빛고을 cd 구축
bitgouel 배포 deploy 쉘 스크립트 작성
bitgouel cd yml 작성
=> create :: bitgouel cd scripts

.github/workflows/bitgouel-cd.yml
cd yml에 secret, access key 경로 설정이 잘못되어있어 재설정했습니다.
=> chore :: AccessKey, SecretKey 환경변수 재설정

.github/workflows/bitgouel-cd.yml
=> chore :: underbar to space

.github/workflows/bitgouel-cd.yml, appspec.yml
code deploy 적용
appspec.yml 추가와 CD 스크립트에 배포 job 추가
=> 88 codedeploy 적용

bitgouel-api/src/main/kotlin/team/msg/domain/health/HealthCheckController.kt
healthcheck 반환값에 ResponseEntity를 추가
ResponseEntity 반환값 추가
=> health check controller response entity 적용

bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/AuthController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/request/BbozzakSignUpRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/BbozzakSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/bbozzak/presentation/request/BbozzakSignUpRequest.kt
뽀짝샘 회원가입 API
뽀짝샘 회원가입에 접근권한을 설정해주었습니다.
WebRequest 에 대한 valid 처리를 해주었습니다.
WebRequest 를 비지니스 로직에서 사용하는 dto 로 매핑해 사용합니다.
Response를 201 Created 를 반환해줍니다.
=> # 93 뽀짝샘 회원가입 API

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllLectureRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/web/CreateLectureWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/web/QueryAllLecturesWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureRepository.kt
강의 조회 기능을 작업했습니다.
- 강의 리스트 조회 기능
- 파라미터로 들어온 강의 종류에 따라 필터링 된 결과가 나옵니다.
- 어드민이 아닌 유저는 APPROVE 상태의 강의만 볼 수 있습니다.
- 강의 상세조회 기능
- .noContent() -> .status(HttpStatus.NO_CONTENT)
=> 90 feature/query lecture

bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/ClubRepository.kt
동아리 전체 조회 API 개발
동아리 전체 조회 API 접근 권한 설정을 해주었습니다.
QueryString으로 학교를 받아 그에 맞는 동아리를 반환 해줍니다.
listOf 라는 함수를 만들어 반환 해줍니다.
=> #100 동아리 전체 조회 API 개발

bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/UserController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
마이페이지 조회 기능을 개발했습니다.
- 현재 로그인 된 유저의 마이페이지를 조회하는 기능
- user response pageOf()
개인적으로 when 절을 else if 절보다 좋아해서 user service의 권한별 소속 처리 부분을 when 절로 작성하긴 했으나, 더 좋은 방법이 있다면 알려주세요!
=> 97 feature/query user my page

bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
학생이 자신의 학생 활동을 조회하는 api를 작성하였습니다
* queryMyStudentActivities service
* queryMyStudentActivities controller
* MyStudentActivities response
학생 활동을 리스트로 반환해줘야 하는 controller, service, response의 함수명에 있는 StudentActivity를 복수형인 StudentActivities로 바꿔주었습니다
=> d99 feat/my studnet activity list

bitgouel-domain/src/main/kotlin/team/msg/domain/post/enums/FeedType.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/post/model/Post.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/post/repository/PostRepository.kt
게시글 도메인을 작성했습니다.
- post entity
- post repository
- feed type
=> 110 feature/setting post domain

bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt
유저 Util을 작성했습니다.
- find~~ByUser() 와 같이 유저를 통해 엔티티를 얻는 기능을 Util에 모았습니다.
- 서비스 구현체마다 find~~ByUser를 UserUtil로 사용하도록 변경했습니다.
=> 112 feature/create user util

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
강의 리스트 전체 조회 response에 빠진 내용을 추가했습니다.
변경 전
```
{
"lectures" : [
{
"id" : UUID
"name" : String,
"startDate" : LocalDateTime,
"endDate" : LocalDateTime,
"completeDate" : LocalDateTime,
"lectureType" : LecuteType,
"lectureStatus" : LectureStatus,
"headCount" : Int,
"maxRegisteredUser" : Int,
}
]
}
```
변경 후
```
{
"lectures" : [
{
"id" : UUID
"name" : String,
"content" : String, // 강의 내용 추가
"startDate" : LocalDateTime,
"endDate" : LocalDateTime,
"completeDate" : LocalDateTime,
"lectureType" : LecuteType,
"lectureStatus" : LectureStatus,
"headCount" : Int,
"maxRegisteredUser" : Int,
"lecturer" : String // 강사 이름 추가
}
]
}
```
=> 강의 리스트 전체 조회 response 요소 추가

bitgouel-api/src/main/kotlin/team/msg/common/init/DataInitializer.kt
init 조건 발생 조건문이 잘못 설정되어 있어 수정합니다.
=> 119 feat/data init count

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
강의 리스트 조회에 response body에 강의 승인 여부를 추가했습니다.
- response body에 approve status 추가
=> 강의 리스트 조회에 response body에 강의 승인 정보 추가

bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
강의 상태 버그를 수정했습니다.
강의 신청이 가능한 기간인데도 강의 상태가 CLOSE인 버그를 고쳤습니다.
if문의 조건절을 변경했습니다.
=> 강의 상태 버그 수정

bitgouel-api/src/main/kotlin/team/msg/domain/certification/exception/ForbiddenCertificationException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/exception/constant/CertificationErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/CertificationController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
자격증 리스트 조회 선생님 api 개발
자격증 리스트 조회 서비스를 오버로딩하여 만들었습니다.
선생님만 접근할 수 있도록 설정해주었습니다.
=> # 136 자격증 리스트 조회 선생님 api 개발

scripts/deploy.sh
=> chore :: deploy sh awk 옵션 삭제

bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
요구사항이 변경됨에 따라 리스트 조회 시 활동 날짜도 포함되어야 합니다
StudentActivitiesResponse 클래스에 activityDate 필드 추가
=> add :: 학생 활동 리스트 조회 Response에 활동날짜 필드 추가

bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt
소속 문자열 슬래시 구분
마이페이지 소속에서 반환되는 문자열을 슬래시로 구분하였습니다.
=> 165 소속 문자열 슬래시 구분

bitgouel-batch/src/main/kotlin/team/msg/common/listener/BatchStepExecutionListener.kt, bitgouel-batch/src/main/kotlin/team/msg/jobs/student/GraduateStudentJobConfiguration.kt
ItemReader 학생 읽어올때 학번 정렬 조건 추가 (ASC는 일부러 붙였습니다.)
Listner 익명 클래스로 지정 (Step의 이름을 더욱 상세히 로깅하기 위해서)
Reader sql 정렬 조건 추가
리스너 클래스 익명 구현으로 스텝 지정
ExecutionListener를 일단 남겨두었습니다.
=> STUDENT Reader ORDER BY, Listener 익명 클래스로 구현

bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/exception/UserAlreadyApprovedException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/exception/constant/UserErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
회원가입 대기중인 유저를 어드민이 수락할 수 있는 API를 개발하였습니다
* aprrove user service
* aprrove user service
* UserAlreadyApprovedException
일단은 이미 수락된 유저를 다시 수락하면 에러를 발생시키도록 하였는데, 이게 살짝 필요한 검증인지 의견 주시면 감사할 것 같습니다
=> 172 유저 회원가입 수락 API

bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
학생 활동 상세 정보 api의 Response 값에 ApproveStatus가 누락되어 있어 추가해주었습니다
StudentActivityDetailResponse에 approveStatus 프로퍼티 추가
=> 183 학생 활동 상세 정보 Response에 approveStatus추가

bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/BbozzakSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/CompanyInstructorSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/GovernmentSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/ProfessorSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/StudentSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/TeacherSignUpWebRequest.kt
전화번호 정규식 추가
회원가입 시 필요한 전화번호 정규식을 추가해 주었습니다.
ex : 01000000000, 01012345678
=> # 188 전화번호 정규식 추가

bitgouel-api/src/main/kotlin/team/msg/domain/post/mapper/PostRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/mapper/PostRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/PostController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/request/CreatePostRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/request/UpdatePostRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/CreatePostWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/UpdatePostWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
게시글 수정 기능을 작성했습니다.
게시글 수정 기능을 작성했습니다.
- 본인 이외의 사용자가 수정 요청 시 예외를 던집니다.
- mapper에 run {} 함수를 적용했습니다.
- 개행이 이상한 부분을 고쳤습니다.
=> 186 게시글 수정 기능 작성

bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/post/enums/FeedType.kt
enum 명을 NOTICE로 변경했습니다.
- feedType enum INFORM -> NOTICE
- when문을 if문으로
- 객체 생성 로직에 .run{} 사용
=> update :: feed type enum INFORM -> NOTICE

bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/PostController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
게시글 삭제 기능을 작업했습니다.
- 게시글 삭제 로직 추가
- security config endpoint 추가
=> 192 게시글 삭제 기능

bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
어드민이 유저의 회원가입을 거절할 수 있는 API를 작성하였습니다
* reject User Sign Up Service
* reject User Sign Up Controller
=> 200 회원가입 거절 API

bitgouel-api/src/main/kotlin/team/msg/common/init/DataInitializer.kt
dataitializer club id 중복 제거
Club id 가 중복되어 저장되지 않은 클럽이 있어 중복을 제거 해주었습니다.
=> # 207 dataitializer club id 중복 제거

bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/request/CreateInquiryRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/CreateInquiryRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/CreateInquiryWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllLecturesWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/Inquiry.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/InquiryAnswer.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/InquiryAnswerRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/InquiryRepository.kt
문의사항 질문, 답변에 대한 엔티티를 세팅했습니다.
빠른 작업을 위해 Create API까지 함께 작업했어요
- 문의사항 질문, 답변 엔티티 세팅
- 문의사항 등록 API
- lecture 파트에 web 패키지가 data 바깥에 있더라구요 넣어주었습니다.
- userUtil에 queryCurrentUserId 라는 함수를 사용해봤어요 userId 값을 필드로 두고있는 엔티티를 저장, 사용할때 유용해보여요
=> 212 feat/inquery api

bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
유저의 상세 정보를 조회하기 위한 API입니다
* query user details Service/Controller
* user details Response
=> 🔀 :: 202 유저 상세정보 조회 API

bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/exception/ForbiddenCommandInquiryException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/exception/InquiryAnswerNotFoundException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/exception/InquiryNotFoundException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/exception/constant/InquiryErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/response/InquiryResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-batch/src/main/kotlin/team/msg/jobs/student/GraduateStudentJobConfiguration.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/InquiryAnswerRepository.kt
문의사항 상세조회, 삭제, 어드민 삭제 api
- 문의사항 상세조회
- 문의사항 삭제 admin user 개발
[depapepe - fake](https://www.youtube.com/watch?v=B4a0X8-hG2c) 데파페페 기타곡 이것도 좋습니다
=> 221 feat/inquiry detail delete

bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/request/CreateInquiryAnswerRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/request/UpdateInquiryRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/CreateInquiryAnswerWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/UpdateInquiryWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/presentation/WithdrawStudentController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/presentation/WithdrawStudentResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/presentation/data/response/WithdrawStudentResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/service/WithdrawService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/service/WithdrawServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/Inquiry.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/withdrow/model/WithdrawStudent.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/withdrow/repository/WithdrawStudentRepository.kt
문의사항 수정, 답변 작성 api 개발
- 문의사항 수정 서비스 비즈니스 로직 작성
- 문희사항 답변 서비스 비즈니스 로직 작성
- update request에 update 하는 로직 넣었습니다. 객체 생성하는 로직이요
- inquiry에 replyAnswer 이라는 함수 넣어서 AnswerStatus ANSWERED로 바꾸게했습니다 객체지향 캡슐, 정보은닉 둘다 적용되니 좋더라구요
기타곡은 아니고 keshi -2 soon 들으세요
=> 223 feat/inquiry update

bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
Find method 오용
Student를 teacherRepository를 이용해 찾고 teacher를 StudentRepository를 이용해 찾아 생기는 이슈를 해결 하였습니다.
=> # 225 Find method 오용

bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/teacher/presentation/data/response/TeacherResponse.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
동아리 상세 조회 선생님 추가 반환
* 동아리 상세 조회 API에 선생님을 추가로 반환 해주었습니다.(아직 개발 단계라 Club에 할당된 선생님이 없을 상태를 대비하여 nullable로 설정 해주었습니다.)
=> # 228 동아리 상세 조회 선생님 추가 반환

bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/response/InquiryResponse.kt
문의사항 리스트의 컨텐츠 생성 일자 타입을 변경했습니다.
문의사항 리스트 response의 createAt 타입을 LocalDateTime에서 LocalDate로 변경해주었습니다.
내가 작성한 문의사항 리스트 조회 (GET /inquiry)
문의사항 리스트 전체 조회 (GET /inquiry/all)
두  api의 response가 변경되었습니다.
=> 문의사항 리스트의 컨텐츠 생성 일자 타입을 변경했습니다.

bitgouel-api/src/main/kotlin/team/msg/domain/user/mapper/UserRequestMapper.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/mapper/UserRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/UserController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/request/ModifyPasswordRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/web/ModifyPasswordWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
비밀번호 변경 api를 작성했습니다.
**PATCH** /user 비밀번호 변경
```json
{
"currentPassword" : "",
"newPassword" : ""
}
```
=> 비밀번호 변경 api를 작성했습니다.

bitgouel-domain/src/main/kotlin/team/msg/domain/government/model/Government.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/professor/model/Professor.kt
동아리 관련 Entity 연관관계 수정
club 1 : government, company, professor N 과 같이 연관관계를 변경 해주었습니다.
=> # 240 동아리 관련 Entity 연관관계 수정

bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/certifiacation/repository/CertificationRepository.kt
* 자격증 조회 취득날짜 기준 내림차순 정렬
* 자격증 상세 조회 service에서 acquisitionDate를 기준으로 내림차순 정렬을 해주었습니다.
=> # 242 자격증 조회 취득날짜 기준 내림차순 정렬

bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentResponse.kt
StudentResponse Authority 프로퍼티 삭제
* StudentResponse 클래스의 Authority 프로퍼티를 삭제 해주었습니다.
* map 함수를 이용해 list 반환하던 것을 listOf() 함수를 이용해 반환 해주었습니다.
=> # 257 StudentResponse Authority 프로퍼티 삭제

bitgouel-api/build.gradle.kts, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/data/response/FaqResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQServiceImpl.kt, bitgouel-api/src/test/kotlin/team/msg/domain/faq/service/FaqServiceImplTest.kt
FAQ 테스트 코드 작성
* 격리 수준을 InstancePerLeaf로 설정해주었습니다.
* FaqServiceImpl 클래스에 대해 테스트 코드를 작성했습니다.
* 언급했던 오류는 faq response fixture에 값을 줬더니 해결됐습니다.
=> # 256 FAQ 테스트 코드 작성

bitgouel-api/src/test/kotlin/team/msg/domain/auth/service/AuthServiceImplTest.kt, bitgouel-api/src/test/kotlin/team/msg/domain/certification/service/CertificationImplTest.kt, bitgouel-api/src/test/kotlin/team/msg/domain/faq/service/FaqServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/InquiryAnswer.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/withdraw/model/WithdrawStudent.kt
* 자격증 service 테스트 코드 작성
* CertificationServiceImpl 클래스에 대해 작성한 테스트 코드입니다.
* 격리 수준을 InstancePerLeaf로 설정해 주었습니다.
* bdd 형태로 작성해 주었습니다.
=> # 261 자격증 service 테스트 코드 작성

bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/response/PostResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/handler/UserEventHandler.kt
게시글 상세 조회 반환 인자 추가
게시글 상세 조회에 작성자가 자신인지 확인하는 인자를 추가로 반환해 주었습니다.
=> # 282 게시글 상세 조회 반환 인자 추가

bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt, bitgouel-api/src/test/kotlin/team/msg/domain/club/service/ClubServiceImplTest.kt
동아리 상세 조회 반환 dto 통합
ClubDetailsResponse 하나로 통합해 주었습니다.
명세서도 같이 변경 했습니다.
=> # 285 동아리 상세 조회 반환 dto 통합

bitgouel-api/src/test/kotlin/team/msg/domain/inquiry/service/InquiryServiceImplTest.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt, bitgouel-api/src/test/kotlin/team/msg/domain/student/service/StudentActivityServiceImplTest.kt
문의사항 서비스 테스트코드 작성
격리 수준을 InstancePerLeaf로 설정해 주었습니다.
kotlinFixture 를 사용해 fixture 설정을 해주었습니다.
InqueryServiceImpl 클래스에 대해 테스트를 작성해 주었습니다.
=> # 295 문의사항 서비스 테스트코드 작성

bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt, bitgouel-api/src/test/kotlin/team/msg/domain/club/service/ClubServiceImplTest.kt
마이페이지와 동아리 학생 리스트에 user id 추가
마이페이지 response에 user id 추가
동아리 학생 리스트에 user id 추가
=> 마이페이지와 동아리 학생 리스트에 user id 추가

bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/test/kotlin/team/msg/domain/certification/service/CertificationServiceImplTest.kt
자격증 전체 조회 Service 수정
자격증 전체 조회 Service 에서 선생님이 아닌 다른 권한의 유저들도 요청을 보낼 수 있도록 하였습니다.
그에 따라 SecurityConfig에서 접근 권한도 변경해 주었습니다.
=> # 310 자격증 전체 조회 Service 수정

bitgouel-domain/src/main/kotlin/team/msg/domain/email/model/EmailAuthentication.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/email/repository/EmailAuthenticationRepository.kt
이메일 도메인을 세팅했습니다.
- redis entity, repository
- redis ttl을 적용시켜 인증 번호의 유효 시간을 적용했습니다.
인증 링크를 클릭하는 데에 5분이면 충분할까요? 😑
=> 이메일 도메인 세팅

bitgouel-api/build.gradle.kts, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/Division.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/Semester.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
강의 수강 신청 결과를 엑셀로 출력하는 API를 작성했습니다
* lectureReceiptStatusExcel 서비스 작성
* createCellWithOptions 확장 함수를 사용 보일러플레이트 코드 최소화
테스트 코드 작성은 다른 pr에 작성하도록 하겠습니다
해당 엑셀 양식입니다
=> 🔀 :: 316 강의 수강 신청 결과 엑셀 출력 API

appspec.yml, bitgouel-api/src/main/kotlin/team/msg/global/security/handler/CustomAccessDeniedHandler.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/handler/CustomAuthenticationEntryPointHandle.kt
Script time out 늘리기
300 초로 늘려줬습니다.
=> # 332 Script time out 늘리기

bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/data/request/QueryUsersRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/data/web/QueryUsersWebRequest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/CustomUserRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/impl/CustomUserRepositoryImpl.kt
ApproveStatus Query String nullable
approve status request 인자를 Nullable로 변경해 주었습니다.
=> # 339 ApproveStatus Query String nullable

bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/handler/UserEventHandler.kt, bitgouel-api/src/test/kotlin/team/msg/domain/admin/service/AdminServiceImplTest.kt, bitgouel-api/src/test/kotlin/team/msg/domain/certification/service/CertificationServiceImplTest.kt
Withdraw User Util
기존에 EventHandler 사용하던 것을 userUtil로 바꿔주었습니다. (EventHandler 를 사용하지 않는 이유는 사용하게 되면 user가 먼저 삭제되게 되어 외래 키 제약 위반을 하게됩니다. 그래서 일단 userUtil 에 메서드로 빼놨습니다.)
그에 따른 테스트 코드도 변경해 주었습니다.
=> # 342 Withdraw User Util

bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/FaqController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/data/response/FaqResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FaqService.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/test/kotlin/team/msg/domain/admin/service/AdminServiceImplTest.kt, bitgouel-api/src/test/kotlin/team/msg/domain/faq/service/FaqServiceImplTest.kt
FAQ 조회 API 병합
faq 상세 조회를 삭제했습니다.
faq 전체 조회에 답변까지 추가로 반환해 주었습니다.
=> # 343 FAQ 조회 API 병합

bitgouel-api/src/main/resources/templates/authentication-email-template.html
이메일 인증 전송 메일 템플릿 변경
이메일 인증 링크 전송 시 띄우던 기존의 템플릿에서 디자인 된 템플릿으로 변경했습니다.
=> 이메일 인증 전송 메일 템플릿 변경

.github/workflows/bitgouel-ci.yml, build.gradle.kts, codecov.yml
=> # 356 테스트 커버리지 측정

bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt
전화번호 반환 형식을 변경했습니다
문자열 슬라이싱으로 전화번호 사이 하이픈을 끼워넣어주었습니다
=> 전화번호 반환 형식 변경

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
return type에 ByteArray 대신 서비스에서 엑셀 파일 write() 을 호출하도록 변경했습니다
=> 🔀 :: 362 fix/lecture excel print

bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
강의 리스트 조회 시 페이징되어 오는 값에 오류가 있어서 바꿔주었습니다.
Resolves: #366
분리된 값만 인식해서 페이지 사이즈가 1이라고 반환하는걸,... count 쿼리를 날려 총 데이터 값을 세어주고 생성 값에 넣어주어서
아래와 같이 고쳐주었어요! 
감사합니디ㅏ
=> fix :: 페이징 옵션 오류

bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt
디자인 변경사항에 유저 리스트 페이지에서 전화번호와 이메일이 추가되었습니다
Resolves: #{372}
유저 리스트 API가 전화번호와 이메일을 반환하도록 변경하였습니다
유저 리스트 Controller 함수명 오타를 수정해주었습니다
유저 상세조회 API를 Deprecated 처리 해 주었습니다
=> 372 add/user query api retrun parameter

bitgouel-api/build.gradle.kts, bitgouel-api/src/main/resources/application-local.yml, bitgouel-api/src/main/resources/application-prod.yml, bitgouel-api/src/main/resources/application.yml, bitgouel-api/src/main/resources/logback-spring.xml, build.gradle.kts
Logback 설정
Active Profile 별 yml 파일을 생성했습니다.
디스코드 연동해서 Active Profile Prod일 때 500 뜨면 디스코드 봇이 에러 로그 띄우도록 설정 했습니다. 
클라우드 워치 연동해서 로그 저장하도록 설정해 주었습니다. 30초마다 스캔하도록 했고, 이미 ec2 내부에서 로그 파일을 저장하고 있기 때문에 따로 로그를 저장하게 만들진 않았습니다.(Prod 일 때만)
환경 변수 노션에 업데이트 해놨습니다.
일단 cloudwatch 연동을 위해 일단 제 개인계정으로 해놨습니다.
=> 365 Logback 설정

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
강의 데이터에 essentialComplete를 추가했습니다.
Resolves: #391 
request/response data 변경 api
POST /lecture 강의 개설
GET /lecture 강의 리스트 조회
GET /lecture/{id} 강의 상세정보 조회
감사합니다
=> 강의 데이터에 essentialComplete 추가

bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
강의 개설 권한을 확대했습니다.
Resolves: #393 
- 강의 개설 권한을 강사도 할 수 있도록 변경했습니다.
- 또한 구분 및 계열, 학과 검색 및 강사 검색 api 권한도 변경해주었습니다.
강사 검색 api도 권한을 확대해주어야 할까 싶어요. 강사 권한은 자신이 강의하는 강의만 추가할 수 있도록 하는걸로 하는 건 어떨지 제안해봅니다.
=>  강의 개설 권한 확대

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
강의 수강 신청 결과를 한눈에 볼 수 있도록 엑셀파일로 집계해주는 기능을 리팩토링 했습니다
Resolves: #399 
본래 출력하던 강의 수강신청 결과가 요구사항이 변경되며 출력되야하는 데이터가 변경되어 
각 학교별로, 학생이 수강신청한 모든 강의를 출력하도록 변경했습니다
엑셀을 출력하는 과정에서 발생하는 쿼리들을 최적화한다고 최대한 최적화 했는데, 중첩 반복문에 여러 쿼리들이 발생하는건 어쩔수 없네요 
개선할 점이 있다면 바로바로 리뷰해주세요
=> 🔀 :: 강의 수강 신청 결과 엑셀 다운로드

bitgouel-api/src/test/kotlin/team/msg/domain/admin/service/AdminServiceImplTest.kt, bitgouel-api/src/test/kotlin/team/msg/domain/auth/service/AuthServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/common/entity/BaseUUIDEntity.kt
변경사항으로 인한 실패하는 테스트 코드 수정
Resolves: #{404}
지금껏 생긴 변경사항으로 테스트가 실패하는 곳이 있어 고쳐주었습니다.
=> # 404 변경사항으로 인한 실패하는 테스트 코드 수정

.github/workflows/bitgouel-cd.yml
build에서 test task 수행 시에 redis connection을 얻어오지 못해 fail 하는 문제를 해결하기 위함입니다
Resolves: #368 
CD yml에 redis를 추가
=> 🔀 :: CD Build 시에 redis 추가

bitgouel-api/build.gradle.kts, bitgouel-api/src/main/kotlin/team/msg/common/aop/lock/TransactionAspect.kt, bitgouel-api/src/main/kotlin/team/msg/common/aop/log/HttpLoggingAspect.kt, bitgouel-api/src/main/kotlin/team/msg/common/util/SecurityUtil.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/BbozzakSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/ChangePasswordWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/CompanyInstructorSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/GovernmentSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/LoginWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/ProfessorSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/StudentSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/TeacherSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/config/PropertiesScanConfig.kt, bitgouel-api/src/main/kotlin/team/msg/global/filter/ExceptionFilter.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/aes/AesProperties.kt, bitgouel-api/src/main/resources/application.yml
로그인 및 회원가입 시 비밀번호 AES 암호화 적용
Resolves: #{410}
Javascript의 CryptoJS 라이브러리와 호환되도록 복호화 함수를 작성했습니다.
기존에 구현되어 있던 Pattern 어노테이션을 통한 validation 코드를 security util로 분리했습니다.
Hashing 클래스를 사용하기 위해 guava dependency를 추가했습니다.
=> # 410 로그인 및 회원가입 시 비밀번호 AES 암호화 적용

bitgouel-api/src/main/kotlin/team/msg/common/util/SecurityUtil.kt
비밀번호 정규식 수정
Resolves: #{412}
비밀번호 정규식을 수정했습니다.
=> # 412 비밀번호 정규식 수정

bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/BbozzakSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/ChangePasswordWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/CompanyInstructorSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/GovernmentSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/LoginWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/ProfessorSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/StudentSignUpWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/TeacherSignUpWebRequest.kt
=> # 418 비밀번호 정규식 변경

bitgouel-api/src/main/kotlin/team/msg/global/config/WebMvcConfig.kt
CORS 설정
Resolves: #{420}
CORS 설정을 했습니다.
=> # 420 CORS 설정

appspec.yml, scripts/deploy.sh
Deploy 과정에서 Pull, Build 과정 추가
Resolves: #{424}
test를 제외하고 build를 돌릴 시 빠르게 build가 가능하여 변경했습니다.
=> # 424 Deploy 과정에서 Pull, Build 과정 추가

appspec.yml
Appspec yml 수정
Resolves: #{426}
경로에 / 를 추가했습니다.
=> # 426 Appspec yml 수정

.github/workflows/bitgouel-cd.yml, bitgouel-api/src/main/resources/application-local.yml, bitgouel-api/src/main/resources/application-prod.yml, bitgouel-api/src/main/resources/application.yml
Profile 별 application yml CD에서 적용
Resolves: #{428}
기존에 application.yml 하나에 전부 하던 작업을 곧 배포이기 때문에 원래대로 수정했습니다.
=> # 428 Profile 별 application yml CD에서 적용

bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
동아리 조회 서비스 주석을 원래대로 되돌렸습니다.
Resolves: #{430}
곧 배포단계이기 때문에 편하게 개발하기 위한 동아리 조회 서비스 주석을 원래대로 되돌렸습니다.
=> # 430 동아리 조회 서비스 주석을 원래대로 되돌렸습니다.

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomLectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomRegisteredLectureRepository.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomRegisteredLectureRepositoryImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/projection/LectureProjection.kt
강의 서비스 코드를 리팩토링했습니다.
근데 DB 튜닝 부분이 좀 더많습니다
그냥 강의 도메인 리팩토링이 됐습니다.
Resolves: #352 
- Void 반환을 Unit 반환으로 변경했습니다.
- Pair 로 반환하던 값을 projection 처리하여 dto로 묶었습니다.
- test code에도 변경사항 적용해주었어요
크게 변경한 부분은 없으니 천천히 봐주세요~!
=> 강의 서비스 코드를 리팩토링했습니다.

bitgouel-api/src/main/kotlin/team/msg/global/config/WebMvcConfig.kt
=> # 448 어드민 도메인 CORS 핸들링

bitgouel-api/src/test/kotlin/team/msg/domain/user/service/UserServiceImplTest.kt
유저 도메인 테스트코드를 작성했습니다.
Resolves: #450 
아래 두 기능에 대해 테스트코드를 작성했습니다.
- 유저 마이페이지 조회
- 유저 비밀번호 변경
=> 유저 도메인 테스트코드를 작성했습니다.

.gitignore, bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/AuthController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/CertificationController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/FaqController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/PostController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/UserController.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/principal/AuthDetailsService.kt, bitgouel-api/src/main/resources/logback-spring.xml, bitgouel-domain/src/main/kotlin/team/msg/domain/admin/model/Admin.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/LectureDate.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/professor/model/Professor.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/school/model/School.kt
반환 타입 Unit으로 통합
Resolves: #{이슈번호}
> PR에서 한 작업을 작성해주세요!
반환 타입 Void -> Unit으로 통합
Discord 에러 로그 봇 및 출력 형식 변경
=> # 454 반환 타입 Unit으로 통합

bitgouel-api/src/main/resources/application-local.yml
autocommit 옵션이 true 일 시에 sql이 실행될 때마다 commit이 일어나는 문제가 있었습니다
Resolves: #460 
datasource로 hikariCP를 사용하는것을 명시
autocommit option을 false로 설정
=> 🔀 :: 460 hikaricp datasource autocommit option false로 설정

bitgouel-api/src/main/resources/application-local.yml
Resolves: #462 
hikari datasource jdbc-url을 datasource url로  변경
=> 🔀  :: rollback datasource.url

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt
강의 최대 수강인원 입력 제한을 삭제했습니다.
Resolves: #464 
=> max registered user 제한 삭제

bitgouel-api/src/main/kotlin/team/msg/domain/university/presentation/UniversityController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/university/presentation/data/response/UniversityResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/university/service/UniversityService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/university/service/UniversityServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/university/repository/UniversityRepository.kt
대학교 리스트 조회 요구사항 발생
Resolves: #485 
대학교 패키지 구조 정리
대학교 리스트 조회 API를 구성
=> 🔀 :: 485 대학교 리스트 조회 API

bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/Address.kt, bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/Document.kt, bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/Meta.kt, bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/RoadAddress.kt, bitgouel-api/src/main/resources/application.yml
앱 내 모든 req, res field가 snake case를 인식하는 버그를 고쳤습니다.
Resolves: #496 
yml에서 SNAKE_CASE를 설정하는 것이 아닌 외부와 통신하는 dto에 @JsonNaming을 붙여주었어요
=>  snake case로 req, res되는 버그

bitgouel-api/src/main/kotlin/team/msg/domain/school/mapper/SchoolRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/data/request/CreateSchoolRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/data/request/UpdateSchoolRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/data/response/SchoolResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/web/CreateSchoolWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/web/UpdateSchoolWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/school/model/School.kt
학교 엔티티 핵심분야 필드 삭제
Resolves: #502
동아리에 핵심분야로 충분히 학교 비지니스 로직을 처리할 수 있다고 생각하여 삭제했습니다.
=> # 502 학교 엔티티 핵심분야 필드 삭제

bitgouel-api/src/test/kotlin/team/msg/domain/university/service/UniversityServiceImplTest.kt
university domain의 서비스 코드를 작성했습니다
Resolves: #503 
서비스 코드의 createUniversity, updateUniversity, queryUniversities의 테스트 코드를 작성하였습니다
=> 🔀 :: 503 test/university domain test code

bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/SchoolController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/data/response/SchoolResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
학교 이름 전체 조회 기능 구현
Resolves: #510
학생, 선생님 .. 등의 역할로 회원가입 시 학교를 선택하기 위해 조회하는 기능입니다.
=> # 510 학교 이름 전체 조회 기능 구현

bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
메인페이지에서 학교 조회를 누구나 할 수 있도록 학교 조회 범위를 누구나 조회할 수 있도록 변경하였습니다
Resolves: #520 
query school service 조회 권한 범위 변경
=> 🔀 :: 학교 조회 권한 범위 변경

bitgouel-api/src/main/kotlin/team/msg/domain/club/mapper/ClubRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/web/request/CreateClubWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/web/request/UpdateClubWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/mapper/SchoolRequestMapperImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/data/response/SchoolResponse.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/web/CreateSchoolWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/web/UpdateSchoolWebRequest.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt, bitgouel-api/src/test/kotlin/team/msg/domain/university/service/UniversityServiceImplTest.kt
School/Club 반환 인자 일관성 유지
Resolves: #527 
Club과 School의 반환 인자 일관성을 유지하기 위해 변경한 내용입니다.
=> # 527 School/Club 반환 인자 일관성 유지

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
강의 이수결과 또는 신청 결과를 한눈에 보기 위해서 강의 수강신청결과 엑셀 출력 양식을 변경하였습니다
Resolves: #518 
강의 수강신청결과 엑셀 출력 양식 변경
삽입할 데이터를 반복문들 돌게 되면 재사용하게 되는 것들이 많이 분리하려 하였지만 삽입할 데이터들이 한곳에서 여러 곳으로 퍼지니 가독성이 떨어지는 것 같아 적용하지 않았습니다
그리고 이런 기능들을 테스트하려면 여러 테이블들에 데이터를 삽입해주어야 하는데 이 과정이 좀 번거롭더군요. 뭔가 데이터를 삽입해주거나 쿼리문을 미리 짜놓는 방법이라던가 이런 방안들을 찾아보아야겠습니다.
=> 518 update/lecture registration result excel print form

bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/SchoolController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
학교 수정 후 개별 학교 정보를 다시 가져오기 위해 필요해 작성했습니다
Resolves: #530 
- 강의 상세 정보 조회 API 작성
=> 학교 상세 조회 API를 작성했습니다.

bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt
휴대폰 번호 서식 String 으로 변경
Resolves: #534
휴대폰 번호 셀 부분에 커스텀 서식을 사용하거나 숫자 서식을 사용하면 오류가 발생하여 변경했습니다.
=> # 534 휴대폰 번호 서식 String 으로 변경

bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureDateRepositoryImpl.kt
강의 현재 수강 이수 완료 날짜를 반환하는 메소드가 최신 날짜가 아닌 이전의 날짜를 반환하고 있었습니다
Resolves: #542 
질의 시 정렬 조건을 오름차순으로 변경하였습니다
=> update :: query lecture date desc -> asc

bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
컬럼의 updatable이 false로 되어있어 생긴 문제였습니다. 
Resolves: #544 
updatable true로 변경
=> 강의 신청 시작일과 마감일이 변경되지 않는 오류를 고쳤습니다

.github/workflows/bitgouel-cd.yml
copy deploy script 삭제
Resolves: #547
deploy script를 실행시키는 것에 필요없는 과정같아 삭제합니다.
=> # 547 copy deploy script 삭제

bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt
InputStream close
Resolves: #549
https://github.com/School-of-Company/Bitgouel-Server/pull/546#discussion_r1713105683
위 리뷰에 대한 반영입니다.
=> # 549 InputStream close

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
연번이 증가하지 않아 데이터가 덮어씌워지던 문제가 발생했습니다
Resolves: #554 
인덱스 값이 자동증가하도록 수정하였습니다
=> 🔀 :: 인덱스 자동증가 

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
강의 이수 완료 취소 API를 작성했습니다.
Resolves: #557 
강의 이수 완료 취소 API 작성
=> 강의 이수 완료 취소 API 작성

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
많은 수의 데이터 조회로 인한 서버의 부하와 메모리 사용량을 최적화하기 위해 작업을 하게 되었습니다
Resolves: #563 
중첩된 for 문을 람다 함수로 분리하였습니다
asSequence를 사용하여 실제 데이터가 사용될 때 연산이 일어나도록 하였습니다
=> 🔀 :: 대용량 데이터 조회 및 처리 개선

bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/exception/InvalidFieldException.kt, bitgouel-api/src/main/kotlin/team/msg/domain/club/exception/constant/ClubErrorCode.kt, bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-api/src/test/kotlin/team/msg/domain/admin/service/AdminServiceImplTest.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/user/enums/Authority.kt
동아리 일괄 삽입 기능 개발
Resolves: #568
기존 학생 일괄 삽입 기능과 플로우는 동일합니다. student를 save하느냐 club을 save하느냐의 차이 정도만 있습니다.
=> 568 동아리 일괄 삽입 기능 개발

bitgouel-domain/src/main/kotlin/team/msg/domain/club/model/Club.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/government/model/Government.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/post/model/Post.kt
Club/Government Name Field Unique
Resolves: #576
학교와 유관기관 이름을 Unique로 설정했습니다.
=> # 576 Club/Government Name Field Unique

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt, bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt, bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt, bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
요구사항에 따라 강의별로 시트를 나누어 신청 결과를 출력하는 API를 작성하게 되었습니다 
Resolves: #578 
> 작업을 끝내야할 시간이 얼마 없어 성능보다는 동작을 위주로 만들었습니다
=> 🔀 :: 578 강의 신청 결과 강의별 출력 API

bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
Resolves: #580 
lectureReceiptStatusExcel api Deprecated 처리
=> 🔀 :: 기존 강의 수강 신청 결과 엑셀 출력 API Deprecated 처리
